controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    forward_position_controller:
      type: forward_command_controller/ForwardCommandController

    joint_trajectory_position_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    gravcomp_controller:
      type: moteus_hardware_interface/RobotController

gravcomp_controller:
  ros__parameters:
    joints:
      - joint_1

    command_interfaces:
      - position
      - velocity
      - effort

    state_interfaces:
      - position
      - velocity
      - effort
